export const SAMPLE_WORKORDERS = [
  {
    id: "WO-2026-001", projectName: "I-65 Bridge Replacement", client: "ALDOT",
    clientContact: "Robert Hayes", clientEmail: "rhayes@aldot.gov",
    location: "Mobile County, AL", lat: "30.6954", lng: "-88.0399",
    scope: "12 borings to 80ft, SPT sampling, rock coring below 50ft",
    status: "in-progress", priority: "high", createdDate: "2026-02-10",
    startDate: "2026-02-20", endDate: "2026-03-10", assignedRig: "rig-1",
    assignedCrew: "crew-1", estimatedCost: 85000, submittedBy: "internal",
    borings: [
      { id: "B-1", type: "SPT Boring", plannedDepth: 80, sampleTypes: ["SPT (Split Spoon)", "Rock Core (NX)"], status: "completed" },
      { id: "B-2", type: "SPT Boring", plannedDepth: 80, sampleTypes: ["SPT (Split Spoon)", "Rock Core (NX)"], status: "completed" },
      { id: "B-3", type: "SPT Boring", plannedDepth: 80, sampleTypes: ["SPT (Split Spoon)", "Rock Core (NX)"], status: "in-progress" },
      { id: "B-4", type: "SPT Boring", plannedDepth: 80, sampleTypes: ["SPT (Split Spoon)"], status: "planned" },
      { id: "B-5", type: "SPT Boring", plannedDepth: 60, sampleTypes: ["SPT (Split Spoon)"], status: "planned" },
      { id: "CPT-1", type: "CPT Sounding", plannedDepth: 60, sampleTypes: ["CPT Data"], status: "planned" },
      { id: "CPT-2", type: "CPT Sounding", plannedDepth: 60, sampleTypes: ["CPT Data"], status: "planned" },
      { id: "B-6", type: "SPT Boring", plannedDepth: 80, sampleTypes: ["SPT (Split Spoon)", "Shelby Tube"], status: "planned" },
      { id: "B-7", type: "SPT Boring", plannedDepth: 80, sampleTypes: ["SPT (Split Spoon)"], status: "planned" },
      { id: "B-8", type: "SPT Boring", plannedDepth: 80, sampleTypes: ["SPT (Split Spoon)"], status: "planned" },
      { id: "RC-1", type: "Rock Core Boring", plannedDepth: 100, sampleTypes: ["Rock Core (HQ)"], status: "planned" },
      { id: "RC-2", type: "Rock Core Boring", plannedDepth: 100, sampleTypes: ["Rock Core (HQ)"], status: "planned" },
    ],
  },
  {
    id: "WO-2026-002", projectName: "Waterfront Condo Development", client: "Gulf Coast Developers LLC",
    clientContact: "Sarah Mitchell", clientEmail: "smitchell@gulfcoastdev.com",
    location: "Daphne, AL", lat: "30.6035", lng: "-87.9036",
    scope: "8 borings to 60ft, SPT, 4 monitoring wells",
    status: "scheduled", priority: "medium", createdDate: "2026-02-15",
    startDate: "2026-03-01", endDate: "2026-03-12", assignedRig: "rig-2",
    assignedCrew: "crew-2", estimatedCost: 52000, submittedBy: "external",
    borings: [
      { id: "B-1", type: "SPT Boring", plannedDepth: 60, sampleTypes: ["SPT (Split Spoon)"], status: "planned" },
      { id: "B-2", type: "SPT Boring", plannedDepth: 60, sampleTypes: ["SPT (Split Spoon)"], status: "planned" },
      { id: "B-3", type: "SPT Boring", plannedDepth: 60, sampleTypes: ["SPT (Split Spoon)", "Shelby Tube"], status: "planned" },
      { id: "B-4", type: "SPT Boring", plannedDepth: 60, sampleTypes: ["SPT (Split Spoon)", "Shelby Tube"], status: "planned" },
      { id: "MW-1", type: "Monitoring Well", plannedDepth: 30, sampleTypes: ["Auger Cutting"], status: "planned" },
      { id: "MW-2", type: "Monitoring Well", plannedDepth: 30, sampleTypes: ["Auger Cutting"], status: "planned" },
      { id: "MW-3", type: "Monitoring Well", plannedDepth: 30, sampleTypes: ["Auger Cutting"], status: "planned" },
      { id: "MW-4", type: "Monitoring Well", plannedDepth: 30, sampleTypes: ["Auger Cutting"], status: "planned" },
    ],
  },
  {
    id: "WO-2026-003", projectName: "Municipal Water Tower", client: "City of Fairhope",
    clientContact: "Tom Bradley", clientEmail: "tbradley@fairhopeal.gov",
    location: "Fairhope, AL", lat: "30.5230", lng: "-87.9033",
    scope: "4 deep borings to 100ft, pressuremeter testing, rock coring",
    status: "approved", priority: "low", createdDate: "2026-02-18",
    startDate: "2026-03-15", endDate: "2026-03-22", assignedRig: null,
    assignedCrew: null, estimatedCost: 38000, submittedBy: "external",
    borings: [
      { id: "B-1", type: "Rock Core Boring", plannedDepth: 100, sampleTypes: ["SPT (Split Spoon)", "Rock Core (NX)", "Pressuremeter"], status: "planned" },
      { id: "B-2", type: "Rock Core Boring", plannedDepth: 100, sampleTypes: ["SPT (Split Spoon)", "Rock Core (NX)"], status: "planned" },
      { id: "B-3", type: "SPT Boring", plannedDepth: 80, sampleTypes: ["SPT (Split Spoon)"], status: "planned" },
      { id: "B-4", type: "SPT Boring", plannedDepth: 80, sampleTypes: ["SPT (Split Spoon)"], status: "planned" },
    ],
  },
  {
    id: "WO-2026-004", projectName: "Amazon Distribution Center", client: "Amazon Inc.",
    clientContact: "Kevin Park", clientEmail: "kpark@amazon.com",
    location: "Theodore, AL", lat: "30.5477", lng: "-88.1753",
    scope: "20 borings to 50ft, SPT, environmental screening, 4 CPT soundings",
    status: "pending", priority: "high", createdDate: "2026-02-22",
    startDate: null, endDate: null, assignedRig: null,
    assignedCrew: null, estimatedCost: 95000, submittedBy: "internal",
    borings: [
      ...Array.from({ length: 16 }, (_, i) => ({ id: `B-${i + 1}`, type: "SPT Boring", plannedDepth: 50, sampleTypes: ["SPT (Split Spoon)"], status: "planned" })),
      ...Array.from({ length: 4 }, (_, i) => ({ id: `CPT-${i + 1}`, type: "CPT Sounding", plannedDepth: 50, sampleTypes: ["CPT Data"], status: "planned" })),
    ],
  },
  {
    id: "WO-2026-005", projectName: "Highway 98 Widening Phase 2", client: "ALDOT",
    clientContact: "Maria Gonzalez", clientEmail: "mgonzalez@aldot.gov",
    location: "Baldwin County, AL", lat: "30.4107", lng: "-87.6836",
    scope: "16 borings along alignment, SPT, pavement coring",
    status: "in-progress", priority: "medium", createdDate: "2026-02-05",
    startDate: "2026-02-18", endDate: "2026-03-05", assignedRig: "rig-3",
    assignedCrew: "crew-3", estimatedCost: 62000, submittedBy: "internal",
    borings: Array.from({ length: 16 }, (_, i) => ({
      id: `B-${i + 1}`, type: "SPT Boring", plannedDepth: 45, sampleTypes: ["SPT (Split Spoon)"],
      status: i < 7 ? "completed" : i === 7 ? "in-progress" : "planned",
    })),
  },
];

export const SAMPLE_DAILY_REPORTS = [
  {
    id: "DR-001", workOrderId: "WO-2026-001", date: "2026-02-24",
    crew: "crew-1", rig: "rig-1", driller: "Martinez",
    startTime: "07:00", endTime: "17:00", weatherConditions: "Clear, 58°F",
    equipmentIssues: "None", safetyIncidents: "None",
    notes: "Encountered harder formation than expected below 35ft on B-3. May need to core tomorrow.",
    boringLogs: [
      { boringId: "B-3", type: "SPT Boring", startDepth: 0, endDepth: 42, soilConditions: "Sandy clay 0-25ft, transition to limestone at 38ft", samplesCollected: 8, sampleTypes: ["SPT (Split Spoon)"], sptBlowCounts: "12/15/18, 14/16/20, 22/25/30, 35/40/50", waterLevel: "18 ft", footage: 42 },
    ],
    billingEntries: [
      { unit: "Hourly Drilling", quantity: 8.5, rate: 285 },
      { unit: "SPT Samples", quantity: 8, rate: 45 },
      { unit: "Mobilization", quantity: 1, rate: 1500 },
    ],
    status: "submitted", reviewNotes: "",
  },
  {
    id: "DR-002", workOrderId: "WO-2026-001", date: "2026-02-25",
    crew: "crew-1", rig: "rig-1", driller: "Martinez",
    startTime: "07:00", endTime: "16:30", weatherConditions: "Partly cloudy, 62°F",
    equipmentIssues: "Replaced core barrel bit at 55ft", safetyIncidents: "None",
    notes: "Completed rock coring from 45-78ft on B-3. Good recovery 85%. Started B-4 late afternoon.",
    boringLogs: [
      { boringId: "B-3", type: "Rock Core Boring", startDepth: 42, endDepth: 78, soilConditions: "Limestone with clay seams 42-60ft, competent limestone below", samplesCollected: 6, sampleTypes: ["Rock Core (NX)"], sptBlowCounts: "50/50+, refusal at 45ft - switched to coring", waterLevel: "18 ft", footage: 36 },
      { boringId: "B-4", type: "SPT Boring", startDepth: 0, endDepth: 15, soilConditions: "Sandy clay, soft to medium stiff", samplesCollected: 3, sampleTypes: ["SPT (Split Spoon)"], sptBlowCounts: "8/10/12, 10/12/14", waterLevel: "Not encountered", footage: 15 },
    ],
    billingEntries: [
      { unit: "Hourly Drilling", quantity: 8, rate: 285 },
      { unit: "Rock Coring", quantity: 36, rate: 65 },
      { unit: "SPT Samples", quantity: 3, rate: 45 },
      { unit: "Per Foot", quantity: 15, rate: 22 },
    ],
    status: "submitted", reviewNotes: "",
  },
  {
    id: "DR-003", workOrderId: "WO-2026-005", date: "2026-02-25",
    crew: "crew-3", rig: "rig-3", driller: "Williams",
    startTime: "06:30", endTime: "15:00", weatherConditions: "Overcast, 55°F, light rain AM",
    equipmentIssues: "None", safetyIncidents: "None - traffic control in place",
    notes: "Completed B-7 and started B-8. Good progress despite morning rain delay (1hr).",
    boringLogs: [
      { boringId: "B-7", type: "SPT Boring", startDepth: 0, endDepth: 45, soilConditions: "Sand 0-15ft, sandy clay 15-35ft, stiff clay to TD", samplesCollected: 9, sampleTypes: ["SPT (Split Spoon)"], sptBlowCounts: "5/7/8, 8/10/12, 12/14/16, 15/18/22", waterLevel: "12 ft", footage: 45 },
      { boringId: "B-8", type: "SPT Boring", startDepth: 0, endDepth: 20, soilConditions: "Sand 0-12ft, sandy clay below", samplesCollected: 4, sampleTypes: ["SPT (Split Spoon)"], sptBlowCounts: "4/6/7, 7/9/11", waterLevel: "10 ft", footage: 20 },
    ],
    billingEntries: [
      { unit: "Hourly Drilling", quantity: 7.5, rate: 285 },
      { unit: "SPT Samples", quantity: 13, rate: 45 },
      { unit: "Traffic Control", quantity: 1, rate: 850 },
      { unit: "Per Foot", quantity: 65, rate: 22 },
    ],
    status: "approved", reviewNotes: "Good production. Approved - MG",
  },
];
